MvcTask/Areas/admin/Models/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MvcTask.Areas.admin.Models
{
    public class Article
    {
        public DAO.Model.Article OriginArticle
        {
            get
            {
                return new DAO.Model.Article
                {
                    ArticleId = ArticleId,
                    Date = Date,
                    Title = Title,
                    Text = Text
                };
            }
        }

        public long ArticleId { get; set; }

        [Required]
        [Display(Name = "Дата создания")]
        [DataType(DataType.DateTime)]
        public DateTime Date { get; set; }

        [Required]
        [Display(Name = "Заголовок статьи")]
        public string Title { get; set; }

        [DataType(DataType.MultilineText)]
        [Required]
        [Display(Name = "Содержимое")]
        public string Text { get; set; }

        [Display(Name = "Теги")]
        public List<long> Tags { get; set; }
    }
}

MvcTask/Models/PreviewArticle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcTask.Models
{
    public class PreviewArticle
    {
        public long ArticleId { get; set; }
        public DateTime Date { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
    }
}

MvcTask/Areas/admin/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using BBL;
using DAO.Repository;
using EntityFrameworkDAO.Repository;
//using DAO.Model;
using MvcTask.Models;
using MvcTask.Areas.admin.Models;
using MvcTask.SetupMapper;

namespace MvcTask.Areas.admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ArticleController : Controller
    {
        //
        // GET: /admin/Article/
        IArticleRepositry repo = new EntityFrameworkArticleRepository();
        ITagRepository repoTag = new EntityFrameworkTagRepository();

        public ActionResult Index()
        {
            ArticleMapper.MapForPreview(200);
            return View(repo.GetAll().Select(Mapper.Map<DAO.Model.Article, PreviewArticle>));
        }

        //
        // GET: /admin/Article/Details/5

        public ActionResult Details(int id = 0)
        {
            var article = repo.FindById(id);
            if (article == null)
                return HttpNotFound();
            return View(article);
        }

        //
        // GET: /admin/Article/Create

        public ActionResult Create()
        {
            TempData["Tags"] = repoTag.GetAll().Select(t => new SelectListItem { Text = t.Title, Value = t.TagId.ToString() });
            TempData.Keep("Tags");
            return View();
        }

        //
        // POST: /admin/Article/Create

        [HttpPost]
        public ActionResult Create(Article article)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var origin = article.OriginArticle;
                    origin.Tags = TagWorker.FindTagsById(repoTag, article.Tags);
                    repo.Add(origin);
                    return RedirectToAction("Index");
                }
            }
            catch
            {

            }
            TempData.Keep("Tags");
            return View(article);
        }

        //
        // GET: /admin/Article/Edit/5

        public ActionResult Edit(int id)
        {
            TempData["AllTags"] = repoTag.GetAll();
            TempData.Keep("AllTags");
            ArticleMapper.MapForEditing();
            return View(Mapper.Map<DAO.Model.Article, Article>(repo.FindById(id)));
        }

        //
        // POST: /admin/Article/Edit/5

        [HttpPost]
        public ActionResult Edit(Article article)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var origin = article.OriginArticle;
                    origin.Tags = TagWorker.FindTagsById(repoTag, article.Tags);
                    repo.Edit(origin);
                    return RedirectToAction("Index");
                }
            }
            catch
            {

            }
            TempData.Keep("AllTags");
            return View(article);
        }

        //
        // GET: /admin/Article/Delete/5

        public ActionResult Delete(int id)
        {
            return View(repo.FindById(id));
        }

        //
        // POST: /admin/Article/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                repo.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MvcTask/Controllers/VoiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO.Repository;
using DAO.Model;

namespace MvcTask.Controllers
{
    public class VoiteController : Controller
    {
        IVoiteRepository repo = new EntityFrameworkDAO.Repository.EntityFrameworkVoiteRepository();

        public ActionResult Index()
        {
            return PartialView();
        }

        [OutputCache(Duration = 60000)]
        public ActionResult Summary()
        {
            ViewBag.Summary = repo.Summary();
            return PartialView();
        }

        //
        // GET: /Voite/

        public ActionResult Voite(Voite v)
        {
            repo.Add(v);
            return RedirectToAction("Index", "Home");
        }

    }
}

MvcTask/Views/Shared/Article.cshtml
@model DAO.Model.Article

<div class="post_box">

    <h2><a href="#">@Model.Title</a></h2>
    <div class="news_meta">Создано @Model.Date.ToLongDateString() @Model.Date.ToShortTimeString() </div>
    <!--<div class="image_wrapper"><a href="" target="_parent"><img alt="image 1" /></a></div>-->
    <p align="justify">@Model.Text</p>
    <div class="cleaner"></div>
</div>

MvcTask/Views/Shared/Menu.cshtml
@using MvcTask.Helper;
@Html.UlList(new List<MvcHtmlString> {
    Html.ActionLink("Главная","Index", new{area = "", controller = "Home"}),
    Html.ActionLink("Гостевая","Index", new{area = "", controller = "Guest"}),
    Html.ActionLink("Анкета","Index", new{area = "", controller = "Form"})},
    "menu")

MvcTask/Views/Shared/PreviewArticle.cshtml
@model MvcTask.Models.PreviewArticle

<div class="post_box">

    <h2>
        @Html.ActionLink(Model.Title, "Article", new { id = Model.ArticleId })
    </h2>
    <div class="news_meta">Создано @Model.Date.ToLongDateString() @Model.Date.ToShortTimeString() </div>
    <!--<div class="image_wrapper"><a href="" target="_parent"><img alt="image 1" /></a></div>-->
    <p align="justify">@Model.Text</p>
    @using (Html.BeginForm("Article", "Home", FormMethod.Get))
    {
        @Html.Hidden("id", Model.ArticleId)
        <input type="submit" value="Подброднее" class="continue" />
    }
    <div class="cleaner"></div>
</div>

MvcTask/Views/Shared/Review.cshtml
@model DAO.Model.Review

<div class="review">

    <div class="avatar">
        <img width="50" height="50" class="avatar" src="~/Content/images/user-01.png" alt="">
    </div>

    <div class="comment-info">
        <cite>@Model.Name</cite>

        <div class="comment-meta">
            <time class="comment-time">@Model.Date.ToLongDateString() @Model.Date.ToShortTimeString() </time>
        </div>
    </div>

    <div class="comment-text">
        <p>
            @Model.Text
        </p>
    </div>

</div>

MvcTask/Views/Shared/_Layout.cshtml
<!--<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <title>ViewBag.Title</title>
    RenderSection("styles", false)
    RenderSection("scripts", false)
</head>
<body>
    <header id="top">
        <div id="logo"></div>
        <div id="title">
            <h1>ViewBag.Title</h1>
        </div>
        RenderSection("head", false)
    </header>
    <div id="content">
        <div id="right">
            Html.Partial("Menu")
        </div>
        <div id="main">
            RenderSection("body")
        </div>

    </div>
    <footer>
        <div id="copyright">&copy; 2015 Power by Stas</div>
        <a href="#top" id="up"></a>
    </footer>
</body>
</html>-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/templatemo_style.css" rel="stylesheet" />
    <script src="~/Content/js/jquery-2.1.4.js"></script>
    @RenderSection("styles", false)
    @RenderSection("scripts", false)
    <script language="javascript" type="text/javascript">
        function clearText(field) {
            if (field.defaultValue == field.value) field.value = '';
            else if (field.value == '') field.value = field.defaultValue;
        }
    </script>
</head>
<body>
    <div id="templatemo_body_wrapper">
        <div id="templatemo_wrapper">

            <div id="templatemo_header">

                <div id="site_title">
                    <a href="/" target="_parent">
                        Stas
                        <span>Blog</span>
                        <span class="tagline">@ViewBag.Title</span>
                    </a>
                </div> <!-- end of site_title -->
                <!--
                    <div id="search_box">
                        <form action="#" method="get">
                            <input type="text" placeholder="Поиск..." name="q" size="10" id="searchfield" title="searchfield"/>
                            <input type="submit" name="Search" value="Искать" id="searchbutton" title="Search"/>
                        </form>
                    </div>
                -->


                <div class="cleaner"></div>

            </div> <!-- end of header -->

            <div id="templatemo_menu">
                @Html.Partial("Menu")


                @Html.Partial("_LoginPartial")
            </div> <!-- end of templatemo_menu -->

            <div id="templatemo_main">

                <div id="templatemo_content">

                    @RenderSection("body", true)

                </div>

                <div id="templatemo_sidebar">
                    @Html.Action("Summary", "Voite")
                    @RenderSection("right", false)
                    <!--
                    <div id="aboutus">
                        <h3>About Design Blog</h3>
                        <div class="image_fl"><img src="~/Content/images/templatemo_about.jpg" alt="about this blog"/></div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras volutpat aliquet risus, a ornare orci scelerisque et. <a href="#" class="continue">more...</a></p>
                    </div>

                    <div class="cleaner_h20"></div>

                    <div class="sidebar_box">

                        <h3>Our Sponsors</h3>

                        <div class="ads_125"><a href="http://www.templatemo.com/page/1" target="_parent"><img src="~/Content/images/ads_125.jpg" alt="ad 1"/></a></div>
                        <div class="ads_125 odd"><a href="http://www.templatemo.com/page/2" target="_parent"><img src="~/Content/images/ads_125.jpg" alt="ad 2"/></a></div>

                        <div class="ads_125"><a href="http://www.templatemo.com/page/3" target="_parent"><img src="~/Content/images/ads_125.jpg" alt="ad 3"/></a></div>
                        <div class="ads_125 odd"><a href="http://www.templatemo.com/page/4" target="_parent"><img src="~/Content/images/ads_125.jpg" alt="ad 4"/></a></div>

                        <div class="cleaner"></div>

                    </div>

                    <div class="sidebar_box">
                        <h3>Categories</h3>

                        <ul class="sidebar_menu">
                            <li><a href="#">&raquo; Web Design Tips <span>(260)</span></a></li>
                            <li><a href="#">&raquo; Beautiful Wallpapers <span>(380)</span></a></li>
                            <li><a href="#">&raquo; Free Fonts <span>(125)</span></a></li>
                            <li><a href="#">&raquo; Digital Illustrations <span>(215)</span></a></li>
                        </ul>

                    </div>


                    <div class="sidebar_box">
                        <h3>Archives</h3>
                        <ul class="sm_two_col">
                            <li><a href="#">&raquo; February 2048</a></li>
                            <li><a href="#">&raquo; January 2048</a></li>
                            <li class="cleaner"><a href="#">&raquo; December 2047</a></li>
                            <li><a href="#">&raquo; Novermber 2047</a></li>
                            <li><a href="#">&raquo; October 2047</a></li>
                            <li><a href="#">&raquo; September 2047</a></li>
                        </ul>

                        <div class="cleaner"></div>
                    </div>


                    <div class="sidebar_box">

                        <h3>Newsletter</h3>

                        <form method="get" action="#">
                            <input type="text" id="user" name="user" class="newsletter_email" placeholder="Enter your email address"/>
                            <input style="font-weight: bold;" type="submit" name="submit" id="submit" value="Subscribe"/>
                        </form>

                        <div class="cleaner_h20"></div>
                        <a href="#" class="icon_link"><img src="~/Content/images/templatemo_rss.jpg" alt="rss"/></a><a href="#" class="icon_link"><img src="~/Content/images/templatemo_twitter.jpg" alt="twitter"/></a>
                    </div>
                    -->

                </div>

                <div class="cleaner"></div>
            </div>

        </div>
        <div class="cleaner"></div>
    </div>

    <!--
    <div id="templatemo_footer_wrapper">
        <div id="templatemo_footer">

            <div class="footer_box col_w300">
                <h4>Related Posts</h4>
                <ul class="footer_menu">
                    <li><a href="#">Duis vitae velit sed lesuada dignissim</a></li>
                    <li><a href="#">Donec mollis aliquet ligula</a></li>
                    <li><a href="#">Maecenas adipiscing elementum ipsum</a></li>
                    <li><a href="#">Vivamus leo velit, convallis id</a></li>
                    <li><a href="#">Curabitur condimentum porttitor</a></li>
                </ul>
            </div>

            <div class="footer_box col_w160">
                <h4>Authors</h4>
                <ul class="footer_menu">
                    <li><a href="#">Lesuada digni</a></li>
                    <li><a href="#">Aliquet ligula</a></li>
                    <li><a href="#">Convallis id</a></li>
                    <li><a href="#">Maecenas adipis</a></li>
                    <li><a href="#">Porttitor</a></li>
                </ul>
            </div>

            <div class="footer_box col_w160">
                <h4>Partners</h4>
                <ul class="footer_menu">
                    <li><a href="http://www.flashmo.com/page/1" target="_parent">Flash Components</a></li>
                    <li><a href="http://www.templatemo.com/page/1" target="_parent">Website Templates</a></li>
                    <li><a href="http://www.webdesignmo.com/blog" target="_parent">Web Design</a></li>
                    <li><a href="http://www.templatemo.com" target="_parent">CSS Templates</a></li>
                    <li><a href="http://www.koflash.com" target="_parent">Flash Web Gallery</a></li>
                </ul>
            </div>

            <div class="footer_box col_w260 fb_last">
                <h4>Tag Cloud</h4>
                <a href="#" style="font-size:12px">Aenean</a> <a href="#" style="font-size:11px">Cursus</a> <a href="#" style="font-size:16px">Maecenas</a> <a href="#" style="font-size:11px">Aliquam Ligula</a> <a href="#" style="font-size:20px">Egestas</a> <a href="#" style="font-size:16px">Suscipit</a> <a href="#" style="font-size:12px">Sapien</a> <a href="#" style="font-size:28px">Dignissim</a> <a href="#" style="font-size:14px">Vestibulum</a> <a href="#" style="font-size:12px">Lorem</a> <a href="#" style="font-size:14px">Urnain</a> <a href="#" style="font-size:20px">Neque</a> <a href="#" style="font-size:12px">Aenean</a>
            </div>

            <div class="cleaner"></div>
        </div>
    </div>
    -->

    <div id="templatemo_copyright">
        Copyright © 2015 Stas
    </div>
    <a href="#top" id="bt_up"></a>
    <script>
        $(document).ready(function () {
            var url = '/@ViewContext.RouteData.Values["controller"]/@ViewContext.RouteData.Values["action"]';
            var res = url.replace(/Home/, '').replace(/\/Index/, '');
            $('a[href="' + res + '"]').addClass('current');
            $('#templatemo_menu li>a').prepend('<span></span>');
        })

    </script>
</body>
</html>