MvcTask/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO.Model;
using DAO.Repository;
using EntityFrameworkDAO.Repository;

namespace MvcTask.Controllers
{
    public class GuestController : Controller
    {
        private IReviewRepository repo = new EntityFrameworkReviewRepository();

        //
        // GET: /Guest/

        public ActionResult Index()
        {
            ViewBag.Reviews = repo.GetFirtNItem(5);
            return View();
        }

        [HttpPost]
        public ActionResult Registration(Review review)
        {
            try
            {
                ViewBag.Name = review.Name;
                repo.Add(review);
                return View();
            }
            catch (Exception)
            {
                return View("Index", review);
            }
        }

    }
}

MvcTask/Views/Guest/Index.cshtml
@using DAO.Model
@using MvcTask.Helper;
@model DAO.Model.Review
@{
    ViewBag.Title = "Отзывы";
}

@section styles
{
    <link href="~/Content/css/guest.css" rel="stylesheet" />
}

@section right{
    @using (Html.BeginRightBlock("Отзывы"))
    {
        <div class="reviews">
            @foreach (Review i in @ViewBag.Reviews)
            {
                @Html.Partial("Review", i)
            }
        </div>
    }
}

@section body{
    <h2>Оставить отзыв</h2>
    @using (Html.BeginForm("Registration", "Guest"))
    {
        @Html.TextBoxFor(m => m.Name, new { placeholder = "Имя" })
        @Html.Hidden("date", DateTime.Now)
        @Html.TextAreaFor(m => m.Text, new { placeholder = "Отзыв" })
        <input type="submit" value="Отправить" />
    }
}

MvcTask/Views/Guest/Registration.cshtml
@{
    ViewBag.Title = "Отзыв";
}
@section body{
    <h2>Ваш отзыв успешно сохранен</h2>
    @ViewBag.Name, спасибо Вам за отзыв!
}